# Generated by Django 2.1.7 on 2019-04-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
