# Generated by Django 2.1.7 on 2019-04-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_auto_20190331_1459'),
        ('customer', '0016_loggedincustomers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('info', models.TextField(blank=True, max_length=2000, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerProfile')),
            ],
        ),
    ]
