# Generated by Django 2.1.7 on 2019-03-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190328_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test_field',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
