# Generated by Django 2.1.7 on 2019-03-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_userprofile_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(max_length=6),
        ),
    ]
