# Generated by Django 2.1.7 on 2019-03-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20190330_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_type',
        ),
    ]
