# Generated by Django 2.1.7 on 2019-04-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_customerprofile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/customers/'),
        ),
    ]
