# Generated by Django 2.1.7 on 2019-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20190402_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='images/customers/'),
        ),
    ]
