# Generated by Django 2.1.7 on 2019-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20190409_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='photo',
            field=models.ImageField(default='images/customers/default.jpg', upload_to='images/customers/'),
        ),
    ]
