# Generated by Django 2.1.7 on 2019-03-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190330_2316'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service.ServiceType'),
            preserve_default=False,
        ),
    ]
