# Generated by Django 2.1.7 on 2019-03-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='profile_type',
        ),
    ]
