# Generated by Django 2.1.7 on 2019-03-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(default='71645673', max_length=20),
            preserve_default=False,
        ),
    ]
