# Generated by Django 2.1.7 on 2019-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190331_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
