# Generated by Django 2.1.7 on 2019-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0016_loggedincustomers'),
        ('staff', '0004_staffprofile_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('email_from', models.CharField(default='testemailfordjango@gmail.com', max_length=200)),
                ('recipient_list', models.ManyToManyField(to='customer.CustomerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('email_from', models.CharField(default='testemailfordjango@gmail.com', max_length=200)),
                ('recipient_list', models.ManyToManyField(to='staff.StaffProfile')),
            ],
        ),
    ]
