# Generated by Django 2.1.7 on 2019-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_loggedincustomers'),
        ('staff', '0004_staffprofile_average_rating'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecipientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_list', models.ManyToManyField(to='customer.CustomerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRecipientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_list', models.ManyToManyField(to='staff.StaffProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='recipient_list',
        ),
        migrations.RemoveField(
            model_name='staffnewsletter',
            name='recipient_list',
        ),
    ]
