# Generated by Django 2.1.7 on 2019-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20190417_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecipientlist',
            name='recipient_list',
            field=models.ManyToManyField(blank=True, null=True, to='customer.CustomerProfile'),
        ),
        migrations.AlterField(
            model_name='staffrecipientlist',
            name='recipient_list',
            field=models.ManyToManyField(blank=True, null=True, to='staff.StaffProfile'),
        ),
    ]
