# Generated by Django 2.1.7 on 2019-04-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20190417_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='recipient_lsit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsletter.CustomerRecipientList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffnewsletter',
            name='recipient_lsit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsletter.StaffRecipientList'),
            preserve_default=False,
        ),
    ]
