# Generated by Django 2.1.7 on 2019-04-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20190417_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrecipientlist',
            old_name='recipient_list',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='recipient_lsit',
            new_name='recipient_list',
        ),
        migrations.RenameField(
            model_name='staffnewsletter',
            old_name='recipient_lsit',
            new_name='recipient_list',
        ),
        migrations.RenameField(
            model_name='staffrecipientlist',
            old_name='recipient_list',
            new_name='user',
        ),
    ]
