# Generated by Django 2.1.7 on 2019-04-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_auto_20190331_1459'),
        ('customer', '0013_auto_20190402_1256'),
        ('service', '0003_auto_20190330_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(max_length=300)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerProfile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffProfile')),
            ],
        ),
    ]
