# Generated by Django 2.1.7 on 2019-04-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requested_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
