# Generated by Django 2.1.7 on 2019-04-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_requested_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requesting_user_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
