# Generated by Django 2.1.7 on 2019-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_requesting_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejected_requested_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
