# Generated by Django 2.1.7 on 2019-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='default.jpeg', upload_to='images/services/')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
