# Generated by Django 2.1.7 on 2019-03-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='picture',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='icon',
            field=models.FileField(default='default.jpeg', upload_to='images/services/'),
        ),
    ]
