# Generated by Django 2.1.7 on 2019-04-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplocation',
            name='location_text',
            field=models.CharField(default='American University of Beirut', max_length=100),
        ),
    ]
