# Generated by Django 2.1.7 on 2019-03-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnership',
            old_name='name',
            new_name='company_name',
        ),
    ]
