# Generated by Django 2.1.7 on 2019-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190414_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(through='cart.CartProductInfo', to='product.Product'),
        ),
    ]
