# Generated by Django 2.1.7 on 2019-04-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_in_stock'),
        ('cart', '0003_auto_20190414_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProductInfo',
            new_name='CartProduct',
        ),
    ]
